### ISSUE TITLE
no CUDA-capable

### ISSUE THREAD

**Issue by shanguanma** [ShigekiKarita/espnet-semi-supervised#2]
Hi,
I'm reading your the paper. I want to reproduce the experimental results with the code you provided.
but there has been a problem of 'RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:74' in running 'asr_train_loop_th.py', regardless of batch size of 30, 8, 2.

I don't know what's wrong.
errors log:
2019-01-14 15:07:28,360 (asr_train_loop_th:285) INFO: gpu id: 1
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=38 : no CUDA-capable device is detected
Traceback (most recent call last):
  File "scripts/wsj/asr_train_loop_th.py", line 288, in <module>
    model.cuda(gpu_id)  # Copy the model to the GPU
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 111, in _apply
    ret = super(RNNBase, self)._apply(fn)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/home4/md510/espnet/tools/venv/lib/python2.7/site-packages/torch/nn/modules/module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (38) : no CUDA-capable device is detected at /pytorch/aten/src/THC/THCGeneral.cpp:74

**Comment by ShigekiKarita** [comment]
Thank you for report. Which pytorch version are you using? Please consider using 0.3.1.

I have no plan to upgrade pytorch in this repository. Instead, I will upload new code using newer pytorch for my ICASSP2019 paper "SEMI-SUPERVISED END-TO-END SPEECH RECOGNITION USING TEXT-TO-SPEECH AND AUTOENCODERS".

**Comment by ningbiubiu123** [comment]
Thank you very much for your information. May I ask whether you have solved the above problems? Is pyTorch version 0.3.1? Warp_ctc requires a minimum of 0.4 for the PyTorch version. I want to run an error now. What should I do? Hope to get your help
