### ISSUE TITLE
ModuleNotFoundError: No module named 'kaldi_io_py'

### ISSUE THREAD

**Issue by zqs01** [ShigekiKarita/espnet-semi-supervised#4]
Traceback (most recent call last):
  File "/disk3/qszhu/espnet-semi-supervised/python/asr_train_loop_th.py", line 17, in <module>
    from asr_train_th import make_batchset, converter_kaldi, delete_feat
  File "/disk3/qszhu/espnet-semi-supervised/espnet/src/bin/asr_train_th.py", line 32, in <module>
    import lazy_io
  File "/disk3/qszhu/espnet-semi-supervised/espnet/src/utils/lazy_io.py", line 3, in <module>
    from kaldi_io_py import open_or_fd, read_mat, _read_mat_binary
ModuleNotFoundError: No module named 'kaldi_io_py'

How can I solve this problem? thanks.

**Comment by Shafique-Khattak** [comment]
warnings.warn(msg.format(
Traceback (most recent call last):
  File "/mnt/md0/user_ahmed/espnet-semi-supervised/python/asr_train_loop_th.py", line 17, in <module>
    from asr_train_th import make_batchset, converter_kaldi, delete_feat
  File "/mnt/md0/user_ahmed/espnet-semi-supervised/espnet/src/bin/asr_train_th.py", line 32, in <module>
    import lazy_io
  File "/mnt/md0/user_ahmed/espnet-semi-supervised/espnet/src/utils/lazy_io.py", line 3, in <module>
    from kaldi_io_py import open_or_fd, read_mat, _read_mat_binary
ModuleNotFoundError: No module named 'kaldi_io_py'

can you help me with that?
